### ISSUE TITLE
Error inflating class com.jaouan.compoundlayout.CircleGradientRadioLayout?

### ISSUE THREAD

**Issue by nuhkoca** [Jaouan/CompoundLayout#1]
```
23816/com.endroidteam.muhabirce E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.endroidteam.muhabirce, PID: 23816
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.endroidteam.muhabirce/com.endroidteam.muhabirce.activities.DevActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class com.jaouan.compoundlayout.CircleGradientRadioLayout
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2318)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:149)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class com.jaouan.compoundlayout.CircleGradientRadioLayout
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                               at com.endroidteam.muhabirce.activities.DevActivity.onCreate(DevActivity.java:22)
                                                                               at android.app.Activity.performCreate(Activity.java:5411)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:149) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5257) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                               at com.endroidteam.muhabirce.activities.DevActivity.onCreate(DevActivity.java:22) 
                                                                               at android.app.Activity.performCreate(Activity.java:5411) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:149) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5257) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.NoSuchMethodError: android.widget.FrameLayout.<init>
                                                                               at com.jaouan.compoundlayout.CompoundLayout.<init>(CompoundLayout.java:62)
                                                                               at com.jaouan.compoundlayout.RadioLayout.<init>(RadioLayout.java:24)
                                                                               at com.jaouan.compoundlayout.GradientRadioLayout.<init>(GradientRadioLayout.java:65)
                                                                               at com.jaouan.compoundlayout.CircleGradientRadioLayout.<init>(CircleGradientRadioLayout.java:34)
                                                                               at com.jaouan.compoundlayout.CircleGradientRadioLayout.<init>(CircleGradientRadioLayout.java:30)
                                                                               at com.jaouan.compoundlayout.CircleGradientRadioLayout.<init>(CircleGradientRadioLayout.java:26)
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                               at com.endroidteam.muhabirce.activities.DevActivity.onCreate(DevActivity.java:22) 
                                                                               at android.app.Activity.performCreate(Activity.java:5411) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:149) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5257) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by Jaouan** [comment]
I've just fixed an Android<21 issue. And I think your issue should be fixed too.
Be sure that you're not using (Circle)GradientRadioLayout on Android <21. Lollipop (or further) is required to play gradient animation.

Please try to update to 1.0.1.
